### ISSUE TITLE
SGDQ 2022 Monday section visual error

### ISSUE THREAD

**Issue by Superjustinbros** [gman003/gdqrs#2]
On the section devoted to SGDQ 2022's second day (Monday), from the Ty the Tasmanian Tiger run to the Link's Awakening run, the reviews use a much darker, green on black color scheme instead of the cyan-on-grey of normal, non-block runs.
The two Castlevania runs could also be marked as part of the Castlevania block.

**Comment by gman003** [comment]
That block of runs was introduced as Remote Block, hence the terminal-ish color scheme. I decided that took precedence over the Castlevania Block, since it was just two games.

However, I've been thinking about tagging live vs remote runs in some other way, since there were many remote runs scattered outside of the dedicated Remote Block, and I expect some people would like to be able to filter by in-person or online. I don't know how I would want to present this visually, though. I'm open to suggestions.

**Comment by Superjustinbros** [comment]
Hmm, let's see...
Maybe some kind of [RR] (Remote Runner) tag next to the runner's name(s)? Sort of like the [#RH] tags for record holders and a [WR] in the rare instances the run ends up being a world record.

**Comment by gman003** [comment]
That could work - and it could also apply to the rare times when a run happens live, but a commentator joins remotely. It's happened a few times to get dev commentary in, that I can recall. Though it would need a different tag than "Remote Runner". Just [REM] maybe?

**Comment by Superjustinbros** [comment]
Sure, that would work.

**Comment by gman003** [comment]
I've been marking online runners with [REM], but I finally implemented a filter for in-person versus remote in e7f44d7f867dc800ae8780999b68d733f6c59e03 which seems like a suitable point to finally close this ticket.
